apiVersion: azuregaming.com/v1alpha1
kind: DedicatedGameServerCollection
metadata:
  name: openarena-collection-example
spec:
  replicas: 5
  podAutoScalerDetails:
    minimumReplicas: 5
    maximumReplicas: 10
    scaleInThreshold: 60
    scaleOutThreshold: 80
    enabled: true
    coolDownInMinutes: 5
    maxPlayersPerServer: 10
  template: 
    restartPolicy: Never
    dnsPolicy: ClusterFirstWithHostNet
    containers:
    - name: openarena
      image: docker.io/dgkanatsios/docker_openarena_k8s:0.0.5
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 100m
          memory: 32Mi
      env:
      - name: OA_STARTMAP
        value: "dm4ish"
      - name: OA_PORT
        value: "27960"
      volumeMounts:
      - name: openarenavolume
        mountPath: /data
      ports:
      - containerPort: 27960
        protocol: UDP  
    volumes:
    - name: openarenavolume
      azureFile:
        secretName: openarena-storage-secret
        shareName: openarenadata
        readOnly: false
  