/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/pkg/apis/azuregaming/v1alpha1"
	scheme "github.com/dgkanatsios/azuregameserversscalingkubernetes/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PortRegistriesGetter has a method to return a PortRegistryInterface.
// A group's client should implement this interface.
type PortRegistriesGetter interface {
	PortRegistries(namespace string) PortRegistryInterface
}

// PortRegistryInterface has methods to work with PortRegistry resources.
type PortRegistryInterface interface {
	Create(*v1alpha1.PortRegistry) (*v1alpha1.PortRegistry, error)
	Update(*v1alpha1.PortRegistry) (*v1alpha1.PortRegistry, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PortRegistry, error)
	List(opts v1.ListOptions) (*v1alpha1.PortRegistryList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PortRegistry, err error)
	PortRegistryExpansion
}

// portRegistries implements PortRegistryInterface
type portRegistries struct {
	client rest.Interface
	ns     string
}

// newPortRegistries returns a PortRegistries
func newPortRegistries(c *AzuregamingV1alpha1Client, namespace string) *portRegistries {
	return &portRegistries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the portRegistry, and returns the corresponding portRegistry object, and an error if there is any.
func (c *portRegistries) Get(name string, options v1.GetOptions) (result *v1alpha1.PortRegistry, err error) {
	result = &v1alpha1.PortRegistry{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("portregistries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PortRegistries that match those selectors.
func (c *portRegistries) List(opts v1.ListOptions) (result *v1alpha1.PortRegistryList, err error) {
	result = &v1alpha1.PortRegistryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("portregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested portRegistries.
func (c *portRegistries) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("portregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a portRegistry and creates it.  Returns the server's representation of the portRegistry, and an error, if there is any.
func (c *portRegistries) Create(portRegistry *v1alpha1.PortRegistry) (result *v1alpha1.PortRegistry, err error) {
	result = &v1alpha1.PortRegistry{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("portregistries").
		Body(portRegistry).
		Do().
		Into(result)
	return
}

// Update takes the representation of a portRegistry and updates it. Returns the server's representation of the portRegistry, and an error, if there is any.
func (c *portRegistries) Update(portRegistry *v1alpha1.PortRegistry) (result *v1alpha1.PortRegistry, err error) {
	result = &v1alpha1.PortRegistry{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("portregistries").
		Name(portRegistry.Name).
		Body(portRegistry).
		Do().
		Into(result)
	return
}

// Delete takes name of the portRegistry and deletes it. Returns an error if one occurs.
func (c *portRegistries) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("portregistries").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *portRegistries) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("portregistries").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched portRegistry.
func (c *portRegistries) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PortRegistry, err error) {
	result = &v1alpha1.PortRegistry{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("portregistries").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
