apiVersion: azuregaming.com/v1alpha1
kind: DedicatedGameServer
metadata:
  name: simplenodejsudp-example
spec:
  template: 
    restartPolicy: Never
    dnsPolicy: ClusterFirstWithHostNet
    containers:
    - name: simplenodejsudp
      image: docker.io/dgkanatsios/simplenodejsudp:0.0.6
      resources:
        limits:
          cpu: 100m
          memory: 30Mi
        requests:
          cpu: 100m
          memory: 20Mi
      ports:
      - containerPort: 22222
        protocol: UDP