/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	azuregamingv1alpha1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/pkg/apis/azuregaming/v1alpha1"
	versioned "github.com/dgkanatsios/azuregameserversscalingkubernetes/pkg/client/clientset/versioned"
	internalinterfaces "github.com/dgkanatsios/azuregameserversscalingkubernetes/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/pkg/client/listers/azuregaming/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DedicatedGameServerCollectionInformer provides access to a shared informer and lister for
// DedicatedGameServerCollections.
type DedicatedGameServerCollectionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DedicatedGameServerCollectionLister
}

type dedicatedGameServerCollectionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDedicatedGameServerCollectionInformer constructs a new informer for DedicatedGameServerCollection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDedicatedGameServerCollectionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDedicatedGameServerCollectionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDedicatedGameServerCollectionInformer constructs a new informer for DedicatedGameServerCollection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDedicatedGameServerCollectionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuregamingV1alpha1().DedicatedGameServerCollections(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuregamingV1alpha1().DedicatedGameServerCollections(namespace).Watch(options)
			},
		},
		&azuregamingv1alpha1.DedicatedGameServerCollection{},
		resyncPeriod,
		indexers,
	)
}

func (f *dedicatedGameServerCollectionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDedicatedGameServerCollectionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dedicatedGameServerCollectionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azuregamingv1alpha1.DedicatedGameServerCollection{}, f.defaultInformer)
}

func (f *dedicatedGameServerCollectionInformer) Lister() v1alpha1.DedicatedGameServerCollectionLister {
	return v1alpha1.NewDedicatedGameServerCollectionLister(f.Informer().GetIndexer())
}
