# do not forget to set 1. public IPs for the VMs and 2. set the necessary rules on the Network Security Group
apiVersion: v1
kind: Pod
metadata:
  name: openarenapod
  labels:
    name: openarenapod
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: openarenapod
    image: docker.io/dgkanatsios/docker_openarena_k8s:0.0.4
    env:
    - name: OA_STARTMAP
      value: "dm4ish"
    - name: OA_PORT
      value: "27960"
    volumeMounts:
      - name: openarenavolume
        mountPath: /data
    ports:
    - containerPort: 27960
      protocol: UDP  
  volumes:
  - name: openarenavolume
    azureFile:
      secretName: openarena-storage-secret
      shareName: openarenadata
      readOnly: false
