/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/shared/pkg/apis/azuregaming/v1alpha1"
	scheme "github.com/dgkanatsios/azuregameserversscalingkubernetes/shared/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DedicatedGameServerCollectionsGetter has a method to return a DedicatedGameServerCollectionInterface.
// A group's client should implement this interface.
type DedicatedGameServerCollectionsGetter interface {
	DedicatedGameServerCollections(namespace string) DedicatedGameServerCollectionInterface
}

// DedicatedGameServerCollectionInterface has methods to work with DedicatedGameServerCollection resources.
type DedicatedGameServerCollectionInterface interface {
	Create(*v1alpha1.DedicatedGameServerCollection) (*v1alpha1.DedicatedGameServerCollection, error)
	Update(*v1alpha1.DedicatedGameServerCollection) (*v1alpha1.DedicatedGameServerCollection, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DedicatedGameServerCollection, error)
	List(opts v1.ListOptions) (*v1alpha1.DedicatedGameServerCollectionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DedicatedGameServerCollection, err error)
	DedicatedGameServerCollectionExpansion
}

// dedicatedGameServerCollections implements DedicatedGameServerCollectionInterface
type dedicatedGameServerCollections struct {
	client rest.Interface
	ns     string
}

// newDedicatedGameServerCollections returns a DedicatedGameServerCollections
func newDedicatedGameServerCollections(c *AzuregamingV1alpha1Client, namespace string) *dedicatedGameServerCollections {
	return &dedicatedGameServerCollections{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dedicatedGameServerCollection, and returns the corresponding dedicatedGameServerCollection object, and an error if there is any.
func (c *dedicatedGameServerCollections) Get(name string, options v1.GetOptions) (result *v1alpha1.DedicatedGameServerCollection, err error) {
	result = &v1alpha1.DedicatedGameServerCollection{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DedicatedGameServerCollections that match those selectors.
func (c *dedicatedGameServerCollections) List(opts v1.ListOptions) (result *v1alpha1.DedicatedGameServerCollectionList, err error) {
	result = &v1alpha1.DedicatedGameServerCollectionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dedicatedGameServerCollections.
func (c *dedicatedGameServerCollections) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a dedicatedGameServerCollection and creates it.  Returns the server's representation of the dedicatedGameServerCollection, and an error, if there is any.
func (c *dedicatedGameServerCollections) Create(dedicatedGameServerCollection *v1alpha1.DedicatedGameServerCollection) (result *v1alpha1.DedicatedGameServerCollection, err error) {
	result = &v1alpha1.DedicatedGameServerCollection{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		Body(dedicatedGameServerCollection).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dedicatedGameServerCollection and updates it. Returns the server's representation of the dedicatedGameServerCollection, and an error, if there is any.
func (c *dedicatedGameServerCollections) Update(dedicatedGameServerCollection *v1alpha1.DedicatedGameServerCollection) (result *v1alpha1.DedicatedGameServerCollection, err error) {
	result = &v1alpha1.DedicatedGameServerCollection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		Name(dedicatedGameServerCollection.Name).
		Body(dedicatedGameServerCollection).
		Do().
		Into(result)
	return
}

// Delete takes name of the dedicatedGameServerCollection and deletes it. Returns an error if one occurs.
func (c *dedicatedGameServerCollections) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dedicatedGameServerCollections) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dedicatedGameServerCollection.
func (c *dedicatedGameServerCollections) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DedicatedGameServerCollection, err error) {
	result = &v1alpha1.DedicatedGameServerCollection{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dedicatedgameservercollections").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
