/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	multiplayergameserver_v1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/shared/pkg/apis/multiplayergameserver/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiplayerGameServers implements MultiplayerGameServerInterface
type FakeMultiplayerGameServers struct {
	Fake *FakeAzureV1
	ns   string
}

var multiplayergameserversResource = schema.GroupVersionResource{Group: "azure.com", Version: "v1", Resource: "multiplayergameservers"}

var multiplayergameserversKind = schema.GroupVersionKind{Group: "azure.com", Version: "v1", Kind: "MultiplayerGameServer"}

// Get takes name of the multiplayerGameServer, and returns the corresponding multiplayerGameServer object, and an error if there is any.
func (c *FakeMultiplayerGameServers) Get(name string, options v1.GetOptions) (result *multiplayergameserver_v1.MultiplayerGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multiplayergameserversResource, c.ns, name), &multiplayergameserver_v1.MultiplayerGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*multiplayergameserver_v1.MultiplayerGameServer), err
}

// List takes label and field selectors, and returns the list of MultiplayerGameServers that match those selectors.
func (c *FakeMultiplayerGameServers) List(opts v1.ListOptions) (result *multiplayergameserver_v1.MultiplayerGameServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multiplayergameserversResource, multiplayergameserversKind, c.ns, opts), &multiplayergameserver_v1.MultiplayerGameServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &multiplayergameserver_v1.MultiplayerGameServerList{}
	for _, item := range obj.(*multiplayergameserver_v1.MultiplayerGameServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multiplayerGameServers.
func (c *FakeMultiplayerGameServers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multiplayergameserversResource, c.ns, opts))

}

// Create takes the representation of a multiplayerGameServer and creates it.  Returns the server's representation of the multiplayerGameServer, and an error, if there is any.
func (c *FakeMultiplayerGameServers) Create(multiplayerGameServer *multiplayergameserver_v1.MultiplayerGameServer) (result *multiplayergameserver_v1.MultiplayerGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multiplayergameserversResource, c.ns, multiplayerGameServer), &multiplayergameserver_v1.MultiplayerGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*multiplayergameserver_v1.MultiplayerGameServer), err
}

// Update takes the representation of a multiplayerGameServer and updates it. Returns the server's representation of the multiplayerGameServer, and an error, if there is any.
func (c *FakeMultiplayerGameServers) Update(multiplayerGameServer *multiplayergameserver_v1.MultiplayerGameServer) (result *multiplayergameserver_v1.MultiplayerGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multiplayergameserversResource, c.ns, multiplayerGameServer), &multiplayergameserver_v1.MultiplayerGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*multiplayergameserver_v1.MultiplayerGameServer), err
}

// Delete takes name of the multiplayerGameServer and deletes it. Returns an error if one occurs.
func (c *FakeMultiplayerGameServers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multiplayergameserversResource, c.ns, name), &multiplayergameserver_v1.MultiplayerGameServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiplayerGameServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multiplayergameserversResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &multiplayergameserver_v1.MultiplayerGameServerList{})
	return err
}

// Patch applies the patch and returns the patched multiplayerGameServer.
func (c *FakeMultiplayerGameServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *multiplayergameserver_v1.MultiplayerGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multiplayergameserversResource, c.ns, name, data, subresources...), &multiplayergameserver_v1.MultiplayerGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*multiplayergameserver_v1.MultiplayerGameServer), err
}
