/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/pkg/apis/azuregaming/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDedicatedGameServers implements DedicatedGameServerInterface
type FakeDedicatedGameServers struct {
	Fake *FakeAzuregamingV1alpha1
	ns   string
}

var dedicatedgameserversResource = schema.GroupVersionResource{Group: "azuregaming.com", Version: "v1alpha1", Resource: "dedicatedgameservers"}

var dedicatedgameserversKind = schema.GroupVersionKind{Group: "azuregaming.com", Version: "v1alpha1", Kind: "DedicatedGameServer"}

// Get takes name of the dedicatedGameServer, and returns the corresponding dedicatedGameServer object, and an error if there is any.
func (c *FakeDedicatedGameServers) Get(name string, options v1.GetOptions) (result *v1alpha1.DedicatedGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dedicatedgameserversResource, c.ns, name), &v1alpha1.DedicatedGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DedicatedGameServer), err
}

// List takes label and field selectors, and returns the list of DedicatedGameServers that match those selectors.
func (c *FakeDedicatedGameServers) List(opts v1.ListOptions) (result *v1alpha1.DedicatedGameServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dedicatedgameserversResource, dedicatedgameserversKind, c.ns, opts), &v1alpha1.DedicatedGameServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DedicatedGameServerList{ListMeta: obj.(*v1alpha1.DedicatedGameServerList).ListMeta}
	for _, item := range obj.(*v1alpha1.DedicatedGameServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dedicatedGameServers.
func (c *FakeDedicatedGameServers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dedicatedgameserversResource, c.ns, opts))

}

// Create takes the representation of a dedicatedGameServer and creates it.  Returns the server's representation of the dedicatedGameServer, and an error, if there is any.
func (c *FakeDedicatedGameServers) Create(dedicatedGameServer *v1alpha1.DedicatedGameServer) (result *v1alpha1.DedicatedGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dedicatedgameserversResource, c.ns, dedicatedGameServer), &v1alpha1.DedicatedGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DedicatedGameServer), err
}

// Update takes the representation of a dedicatedGameServer and updates it. Returns the server's representation of the dedicatedGameServer, and an error, if there is any.
func (c *FakeDedicatedGameServers) Update(dedicatedGameServer *v1alpha1.DedicatedGameServer) (result *v1alpha1.DedicatedGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dedicatedgameserversResource, c.ns, dedicatedGameServer), &v1alpha1.DedicatedGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DedicatedGameServer), err
}

// Delete takes name of the dedicatedGameServer and deletes it. Returns an error if one occurs.
func (c *FakeDedicatedGameServers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dedicatedgameserversResource, c.ns, name), &v1alpha1.DedicatedGameServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDedicatedGameServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dedicatedgameserversResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DedicatedGameServerList{})
	return err
}

// Patch applies the patch and returns the patched dedicatedGameServer.
func (c *FakeDedicatedGameServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DedicatedGameServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dedicatedgameserversResource, c.ns, name, pt, data, subresources...), &v1alpha1.DedicatedGameServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DedicatedGameServer), err
}
