apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dedicatedgameservercollections.azuregaming.com
spec:
  group: azuregaming.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: DedicatedGameServerCollection
    plural: dedicatedgameservercollections
    singular: dedicatedgameservercollection
    shortNames:
    - dgsc
  additionalPrinterColumns:
  - name: Replicas
    type: string
    description: number of requested replicas
    JSONPath: .spec.activePlayers
  - name: AvailableReplicas
    type: string
    description: state of the game server
    JSONPath: .status.availableReplicas
  - name: Ports
    type: string
    description: ports requested by the server
    JSONPath: .spec.ports
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            Image:
              type: string
              pattern: '^(?!\s*$).+' # non-empty string
            StartMap:
              type: string
              pattern: '^(?!\s*$).+'
            Replicas:
              type: integer
              minimum: 1
              maximum: 100
            AutoScalerDetails:
              type: object
              properties:
                MinimumReplicas:
                  type: integer
                MaximumReplicas:
                  type: integer
                ScaleInThreshold:
                  type: integer
                  minimum: 1
                  maximum: 100
                ScaleOutThreshold:
                  type: integer
                  minimum: 1
                  maximum: 100
                Enabled:
                  type: boolean
                CoolDownInMinutes:
                  type: integer
                LastScaleOperationDateTime:
                  type: string
                MaxPlayersPerServer:
                  type: integer
            Ports:
              type: array
              items:
                type: object
                properties:
                  Name:
                    type: string
                    pattern: '^(?!\s*$).+' # non-empty string
                  ContainerPort:
                    type: integer
                  Protocol:
                    type: string
                    pattern: /^(TCP|UDP)$/
  