apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dedicatedgameservers.azuregaming.com
spec:
  group: azuregaming.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: DedicatedGameServer
    plural: dedicatedgameservers
    singular: dedicatedgameserver
    shortNames:
    - dgs
  # subresources:
  #   # status enables the status subresource.
  #   status: {}
  additionalPrinterColumns:
  - name: ActivePlayers
    type: string
    description: number of active players on the server
    JSONPath: .status.activePlayers
  - name: GameServerState
    type: string
    description: state of the game server
    JSONPath: .status.gameServerState
  - name: PodState
    type: string
    description: state of the game server's pod
    JSONPath: .status.podState
  - name: Ports
    type: string
    description: port mapping of the game server
    JSONPath: .spec.template.containers[0].ports
  - name: PublicIP
    type: string
    description: node's public IP for this DedicatedGameServer
    JSONPath: .status.publicIP