apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dedicatedgameservers.azuregaming.com
spec:
  group: azuregaming.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: DedicatedGameServer
    plural: dedicatedgameservers
    singular: dedicatedgameserver
    shortNames:
    - dgs
  additionalPrinterColumns:
  - name: ActivePlayers
    type: string
    description: number of active players on the server
    JSONPath: .spec.activePlayers
  - name: GameServerState
    type: string
    description: state of the game server
    JSONPath: .status.gameServerState
  - name: PodState
    type: string
    description: state of the game server's pod
    JSONPath: .status.podState
  - name: Ports
    type: string
    description: port mapping of the game server
    JSONPath: .spec.template.containers[0].ports
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            Image:
              type: string
              pattern: '^(?!\s*$).+' # non-empty string
            StartMap:
              type: string
              pattern: '^(?!\s*$).+'
            Ports:
              type: array
              items:
                type: object
                properties:
                  ContainerPort:
                    type: integer
                  Protocol:
                    type: string
                    pattern: /^(TCP|UDP)$/
                  Name:
                    type: string
                    pattern: '^(?!\s*$).+' # non-empty string
                  HostPort:
                    type: integer
                    minimum: 20000
                    maximum: 30000
  