apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dedicatedgameservers.azuregaming.com
spec:
  group: azuregaming.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: DedicatedGameServer
    plural: dedicatedgameservers
    singular: dedicatedgameserver
    shortNames:
    - dgs
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            Image:
              type: string
              pattern: '^(?!\s*$).+' # non-empty string
            StartMap:
              type: string
              pattern: '^(?!\s*$).+'
            Ports:
              type: array
              items:
                type: object
                properties:
                  ContainerPort:
                    type: integer
                  Protocol:
                    type: string
                    pattern: /^(TCP|UDP)$/
                  Name:
                    type: string
                    pattern: '^(?!\s*$).+' # non-empty string
                  HostPort:
                    type: integer
                    minimum: 20000
                    maximum: 30000
  