/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/shared/pkg/apis/multiplayergameserver/v1"
	scheme "github.com/dgkanatsios/azuregameserversscalingkubernetes/shared/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiplayerGameServersGetter has a method to return a MultiplayerGameServerInterface.
// A group's client should implement this interface.
type MultiplayerGameServersGetter interface {
	MultiplayerGameServers(namespace string) MultiplayerGameServerInterface
}

// MultiplayerGameServerInterface has methods to work with MultiplayerGameServer resources.
type MultiplayerGameServerInterface interface {
	Create(*v1.MultiplayerGameServer) (*v1.MultiplayerGameServer, error)
	Update(*v1.MultiplayerGameServer) (*v1.MultiplayerGameServer, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.MultiplayerGameServer, error)
	List(opts meta_v1.ListOptions) (*v1.MultiplayerGameServerList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MultiplayerGameServer, err error)
	MultiplayerGameServerExpansion
}

// multiplayerGameServers implements MultiplayerGameServerInterface
type multiplayerGameServers struct {
	client rest.Interface
	ns     string
}

// newMultiplayerGameServers returns a MultiplayerGameServers
func newMultiplayerGameServers(c *AzureV1Client, namespace string) *multiplayerGameServers {
	return &multiplayerGameServers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multiplayerGameServer, and returns the corresponding multiplayerGameServer object, and an error if there is any.
func (c *multiplayerGameServers) Get(name string, options meta_v1.GetOptions) (result *v1.MultiplayerGameServer, err error) {
	result = &v1.MultiplayerGameServer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiplayergameservers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiplayerGameServers that match those selectors.
func (c *multiplayerGameServers) List(opts meta_v1.ListOptions) (result *v1.MultiplayerGameServerList, err error) {
	result = &v1.MultiplayerGameServerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiplayergameservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiplayerGameServers.
func (c *multiplayerGameServers) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multiplayergameservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a multiplayerGameServer and creates it.  Returns the server's representation of the multiplayerGameServer, and an error, if there is any.
func (c *multiplayerGameServers) Create(multiplayerGameServer *v1.MultiplayerGameServer) (result *v1.MultiplayerGameServer, err error) {
	result = &v1.MultiplayerGameServer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multiplayergameservers").
		Body(multiplayerGameServer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a multiplayerGameServer and updates it. Returns the server's representation of the multiplayerGameServer, and an error, if there is any.
func (c *multiplayerGameServers) Update(multiplayerGameServer *v1.MultiplayerGameServer) (result *v1.MultiplayerGameServer, err error) {
	result = &v1.MultiplayerGameServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiplayergameservers").
		Name(multiplayerGameServer.Name).
		Body(multiplayerGameServer).
		Do().
		Into(result)
	return
}

// Delete takes name of the multiplayerGameServer and deletes it. Returns an error if one occurs.
func (c *multiplayerGameServers) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiplayergameservers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiplayerGameServers) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiplayergameservers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched multiplayerGameServer.
func (c *multiplayerGameServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MultiplayerGameServer, err error) {
	result = &v1.MultiplayerGameServer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multiplayergameservers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
