FROM alpine:3.8
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY /apiserver/cmd/apiserver/apiserver ./
COPY /apiserver/cmd/apiserver/html ./html
CMD ["./apiserver"]
EXPOSE 8000 8001
LABEL Name=aks_gaming_apiserver
