/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/dgkanatsios/azuregameserversscalingkubernetes/shared/pkg/apis/dedicatedgameserver/v1"
	scheme "github.com/dgkanatsios/azuregameserversscalingkubernetes/shared/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DedicatedGameServersGetter has a method to return a DedicatedGameServerInterface.
// A group's client should implement this interface.
type DedicatedGameServersGetter interface {
	DedicatedGameServers(namespace string) DedicatedGameServerInterface
}

// DedicatedGameServerInterface has methods to work with DedicatedGameServer resources.
type DedicatedGameServerInterface interface {
	Create(*v1.DedicatedGameServer) (*v1.DedicatedGameServer, error)
	Update(*v1.DedicatedGameServer) (*v1.DedicatedGameServer, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.DedicatedGameServer, error)
	List(opts meta_v1.ListOptions) (*v1.DedicatedGameServerList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DedicatedGameServer, err error)
	DedicatedGameServerExpansion
}

// dedicatedGameServers implements DedicatedGameServerInterface
type dedicatedGameServers struct {
	client rest.Interface
	ns     string
}

// newDedicatedGameServers returns a DedicatedGameServers
func newDedicatedGameServers(c *AzureV1Client, namespace string) *dedicatedGameServers {
	return &dedicatedGameServers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dedicatedGameServer, and returns the corresponding dedicatedGameServer object, and an error if there is any.
func (c *dedicatedGameServers) Get(name string, options meta_v1.GetOptions) (result *v1.DedicatedGameServer, err error) {
	result = &v1.DedicatedGameServer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DedicatedGameServers that match those selectors.
func (c *dedicatedGameServers) List(opts meta_v1.ListOptions) (result *v1.DedicatedGameServerList, err error) {
	result = &v1.DedicatedGameServerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dedicatedGameServers.
func (c *dedicatedGameServers) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a dedicatedGameServer and creates it.  Returns the server's representation of the dedicatedGameServer, and an error, if there is any.
func (c *dedicatedGameServers) Create(dedicatedGameServer *v1.DedicatedGameServer) (result *v1.DedicatedGameServer, err error) {
	result = &v1.DedicatedGameServer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		Body(dedicatedGameServer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dedicatedGameServer and updates it. Returns the server's representation of the dedicatedGameServer, and an error, if there is any.
func (c *dedicatedGameServers) Update(dedicatedGameServer *v1.DedicatedGameServer) (result *v1.DedicatedGameServer, err error) {
	result = &v1.DedicatedGameServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		Name(dedicatedGameServer.Name).
		Body(dedicatedGameServer).
		Do().
		Into(result)
	return
}

// Delete takes name of the dedicatedGameServer and deletes it. Returns an error if one occurs.
func (c *dedicatedGameServers) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dedicatedGameServers) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dedicatedGameServer.
func (c *dedicatedGameServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DedicatedGameServer, err error) {
	result = &v1.DedicatedGameServer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dedicatedgameservers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
