---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuregamingcontroller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azuregamingcontroller-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: azuregamingcontroller-sa
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-gaming-apiserver
  labels:
    name: aks-gaming-apiserver
spec:
  selector:
    matchLabels: 
      name: aks-gaming-apiserver
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: aks-gaming-apiserver
    spec:
      serviceAccountName: azuregamingcontroller-sa
      containers:
      - name: aks-gaming-apiserver
        image: docker.io/dgkanatsios/aks_gaming_apiserver:0.0.22
        args: ["./apiserver","port","8000"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-gaming-controller
  labels:
    name: aks-gaming-controller
spec:
  selector:
    matchLabels: 
      name: aks-gaming-controller
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: aks-gaming-controller
    spec:
      serviceAccountName: azuregamingcontroller-sa
      containers:
      - name: aks-gaming-controller
        image: docker.io/dgkanatsios/aks_gaming_controller:0.0.22
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aks-gaming-apiserver
  labels:
    name: aks-gaming-apiserver
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: aks-gaming-apiserver
  type: LoadBalancer