---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuregamingcontroller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azuregamingcontroller-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: azuregamingcontroller-sa
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-openarena-k8s-apiserver
  labels:
    name: docker-openarena-k8s-apiserver
spec:
  selector:
    matchLabels: 
      name: docker-openarena-k8s-apiserver
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: docker-openarena-k8s-apiserver
    spec:
      serviceAccountName: azuregamingcontroller-sa
      containers:
      - name: docker-openarena-k8s-apiserver
        image: docker.io/dgkanatsios/aks_gaming_apiserver:0.0.16
        args: ["./apiserver","port","8000"]
        imagePullPolicy: Always
        env:
          - name: STORAGE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: openarena-storage-secret
                key: azurestorageaccountname
          - name: STORAGE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: openarena-storage-secret
                key: azurestorageaccountkey
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-openarena-k8s-controller
  labels:
    name: docker-openarena-k8s-controller
spec:
  selector:
    matchLabels: 
      name: docker-openarena-k8s-controller
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: docker-openarena-k8s-controller
    spec:
      serviceAccountName: azuregamingcontroller-sa
      containers:
      - name: docker-openarena-k8s-controller
        image: docker.io/dgkanatsios/aks_gaming_controller:0.0.16
        imagePullPolicy: Always
        env:
          - name: STORAGE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: openarena-storage-secret
                key: azurestorageaccountname
          - name: STORAGE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: openarena-storage-secret
                key: azurestorageaccountkey        
---
apiVersion: v1
kind: Service
metadata:
  name: docker-openarena-k8s-apiserver
  labels:
    name: docker-openarena-k8s-apiserver
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: docker-openarena-k8s-apiserver
  type: LoadBalancer